### ISSUE TITLE
Love it, But Sloooow

### ISSUE THREAD

**Issue by robmuh** [GeertJohan/gomatrix#11]
Compared to cmatrix, which we have on the system for our students afraid it is too slow to install. I'm guess the algorithm is substantially different. Really too bad because I was going to use it as a replacement for cmatrix to show off Go's capabilities to students. Might be the underlying termbox that is the bottleneck.

**Comment by GeertJohan** [comment]
I wrote this program to play with channels and goroutines. So each falling raindrop/stream is actually a goroutine. So it's not very efficient as it wasn't created with that in mind. There are probably a couple of things that can be improved now that I have more experience with Go. But it might still be fun to look at the code to figure out how the components interact with each other.
