### ISSUE TITLE
--kana not working

### ISSUE THREAD

**Issue by QuentinN42** [GeertJohan/gomatrix#18]
Running `docker run -ti geertjohan/gomatrix -k` in the treminal show that :
```
Opening connection to The Matrix.. Please stand by..
Thank you for connecting with Morpheus' Matrix API v4.2. Have a nice day!
```
![trem](https://user-images.githubusercontent.com/32516498/96339844-5bbab180-1097-11eb-8992-bf9279c49502.png)

Need I install custom font(s) ?
Thanks for this package !

**Comment by misuchiru03** [comment]
You do need to have the fonts the kana fonts installed for them to show.

**Comment by GeertJohan** [comment]
Yes, the fonts are missing in the terminal. There is no way for `gomatrix` to include fonts or select a font, this can only be done in your terminal software.
